spring.datasource.url=jdbc:h2:mem:tests
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

jwt.token.secret=${JWT_SECRET:test-secret}
jwt.token.issuer=test-issuer
jwt.token.zone.offset=-03:00

admin.secret=fake-secret-for-tests