spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=postgres
spring.datasource.password=12345678A.
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.token.secret=${JWT_SECRET:G-AE42c//;::>>>>>>>>AAAAAWW$NzWBMH0C4x`=~#/.Zv13a}
jwt.token.issuer=portfolio
jwt.token.zone.offset=-03:00

admin.secret={AWdwaijwdADWADWJASDMmwWa[~~~~;;;.1===---22331321MNVCAFWWW]]}