import { BackgroundImage } from "@/components/layout/BackgroundImage";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen w-screen antialiased bg-gradient-to-tr from-foreground from-0% to-background to-100%",
                    font.className
                )}
            >
                <BackgroundImage />
                {children}
            </body>
        </html>
    );
}
